### ISSUE TITLE
Node.js tests in CI

### ISSUE THREAD

**Issue by MikeMcC399** [madhusaran/cypress-temp-sms#1]
## Issue

https://github.com/madhusaran/cypress-temp-sms/blob/17dff45677361488fb8333fe6779f2f04e6366aa/.github/workflows/node.js.yml#L19

is not aligned to the [versions of Node.js supported by Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs)

> Node.js 18.x, 20.x, 22.x and above

## Suggestion

Use instead

```yml
node-version: [18.x, 20.x, 22.x] 
```

**Comment by madhusaran** [comment]
@MikeMcC399  Updated as advised.

https://github.com/madhusaran/cypress-temp-sms/blob/17dff45677361488fb8333fe6779f2f04e6366aa/.github/workflows/node.js.yml#L19

**Comment by MikeMcC399** [comment]
@madhusaran 

I just checked your workflow logs https://github.com/madhusaran/cypress-temp-sms/actions/runs/9371340943 and it shows that you should update to `actions/setup-node@v4` (see https://github.com/actions/setup-node)

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by madhusaran** [comment]
@MikeMcC399 Thanks for highlighting the same.

Updated as advised
